export const data = [
  {
    id: 2,
    day: 'Monday',
    cafeteriaMenuType: {
      id: 1,
      nameEnglish: 'Morning Snacks',
      nameHindi: 'सुबह का नाश्ता',
      startTime: '10:00:00',
      endTime: '11:30:00',
    },
    cafeteriaMenuItems: [
      {
        id: 4,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 175,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Upma',
        nameHindi: 'उपमा',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '6',
        isVegetarian: true,
        price: 25.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/9bab87f4-62c9-48d2-bc10-59c793de06ea.jpg',
      },
      {
        id: 5,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 1,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Poha',
        nameHindi: 'पोहा',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'RR',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/ca3ed0df-1eb8-4398-98a6-c87c4beaed14.jpg',
      },
      {
        id: 7,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 12,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Samosa',
        nameHindi: 'समोसा',
        descriptionEnglish: null,
        descriptionHindi: '(कॉकटेल)',
        code: 'm16',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/de10ba94-3448-4554-896f-2948e2347eb2.jpg',
      },
      {
        id: 60,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 260,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'STUFF PARANTHA',
        nameHindi: 'भरवां पराठा',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'API',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 61,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 204,
        maximumPerOrderQuantity: 2,
        nameEnglish: 'Kachori with Chutney',
        nameHindi: 'चटनी के साथ कचौरी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '3',
        isVegetarian: true,
        price: 15.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/28eafad5-d8d9-4fd7-bcd7-b5c2f59393e9.jpg',
      },
      {
        id: 372,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 305,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Ready Made Coffee',
        nameHindi: 'तैयार कॉफ़ी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'C1',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/9c29254e-e799-4d9b-a7e0-683db5bb9857.jpg',
      },
      {
        id: 373,
        availableQuantity: 20,
        masterCafeteriaMenuItemId: 314,
        maximumPerOrderQuantity: 2,
        nameEnglish: 'Masala Tea',
        nameHindi: 'मसाला चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT51',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 661,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 313,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Ready Made Tea',
        nameHindi: 'रेडी मेड चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT50',
        isVegetarian: true,
        price: 5.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/150e4c6f-c41e-448e-b637-2229742d73fe.jpg',
      },
      {
        id: 1059,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 143,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Rice Kheer',
        nameHindi: 'चावल की खीर',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '58',
        isVegetarian: true,
        price: 30.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/1465835a-9242-4d1c-9973-436606f87012.jpg',
      },
    ],
  },
  {
    id: 6,
    day: 'Monday',
    cafeteriaMenuType: {
      id: 2,
      nameEnglish: 'Lunch',
      nameHindi: 'दोपहर का खाना',
      startTime: '12:30:00',
      endTime: '14:30:00',
    },
    cafeteriaMenuItems: [
      {
        id: 18,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 152,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Garden Green Salad',
        nameHindi: 'गार्डन ग्रीन सलाद',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '51',
        isVegetarian: true,
        price: 25.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/f93b1c0b-789d-4e55-9914-047da28fa243.jpg',
      },
      {
        id: 22,
        availableQuantity: 60,
        masterCafeteriaMenuItemId: 99,
        maximumPerOrderQuantity: 4,
        nameEnglish: 'Tawa Roti',
        nameHindi: 'तवा रोटी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '50',
        isVegetarian: true,
        price: 3.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/41aee810-f4e4-420f-949a-d7c204225908.jpg',
      },
      {
        id: 67,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 263,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Dal sultani',
        nameHindi: 'दाल सुल्तानी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT2',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 374,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 103,
        maximumPerOrderQuantity: 2,
        nameEnglish: 'Chicken Curry',
        nameHindi: 'चिकन करी',
        descriptionEnglish: '(2 pcs)',
        descriptionHindi: '(2 पीस)',
        code: '26',
        isVegetarian: false,
        price: 75.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/d7ee6eeb-10bc-48db-b910-c49a6436eca6.jpg',
      },
      {
        id: 376,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 476,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Veg Clear Soup',
        nameHindi: 'सब्जियों का शोरबा',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'VCS',
        isVegetarian: true,
        price: 25.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 378,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 58,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Boiled Rice',
        nameHindi: 'उबले चावल',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '43',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/b85c94b3-b9a9-41d1-b999-5c1d434d6863.jpg',
      },
      {
        id: 379,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 475,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Sweet of the Day',
        nameHindi: 'मिठाई',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'SWT',
        isVegetarian: true,
        price: 15.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 381,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 183,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Vegetable Dry',
        nameHindi: 'वेजीटेबल ड्राइ',
        descriptionEnglish: 'subz miloni',
        descriptionHindi: null,
        code: '40',
        isVegetarian: true,
        price: 35.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/16874b7d-e7e2-47fd-8f8f-e0e63661ae5b.jpg',
      },
      {
        id: 516,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 179,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Veg Thali',
        nameHindi: 'वेज थाली',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '54',
        isVegetarian: true,
        price: 100.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/5a70ca8e-adf2-49ce-8b40-8fef6533bc97.jpg',
      },
      {
        id: 517,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 230,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Mini Thali',
        nameHindi: 'मिनी थाली',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '53',
        isVegetarian: true,
        price: 50.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 541,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 489,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Papad',
        nameHindi: 'पापड़',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'PD1',
        isVegetarian: true,
        price: 3.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 691,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 478,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Raita',
        nameHindi: 'रायता',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'RT01',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 920,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 505,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'PANEER BUTTER MASALA',
        nameHindi: 'पनीर मक्खन मसाला',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'PBM',
        isVegetarian: true,
        price: 60.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
    ],
  },
  {
    id: 7,
    day: 'Monday',
    cafeteriaMenuType: {
      id: 3,
      nameEnglish: 'Evening Snacks',
      nameHindi: 'शाम का नाश्ता',
      startTime: '15:30:00',
      endTime: '17:30:00',
    },
    cafeteriaMenuItems: [
      {
        id: 26,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 12,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Samosa',
        nameHindi: 'समोसा',
        descriptionEnglish: null,
        descriptionHindi: '(कॉकटेल)',
        code: 'm16',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/de10ba94-3448-4554-896f-2948e2347eb2.jpg',
      },
      {
        id: 69,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 204,
        maximumPerOrderQuantity: 2,
        nameEnglish: 'Kachori with Chutney',
        nameHindi: 'चटनी के साथ कचौरी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '3',
        isVegetarian: true,
        price: 15.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/28eafad5-d8d9-4fd7-bcd7-b5c2f59393e9.jpg',
      },
      {
        id: 71,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 257,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Dhokla',
        nameHindi: 'ढोकला',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'm115',
        isVegetarian: true,
        price: 15.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/d7d0a52c-4588-460a-9473-eccd116dc325.jpg',
      },
      {
        id: 384,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 475,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Sweet of the Day',
        nameHindi: 'मिठाई',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'SWT',
        isVegetarian: true,
        price: 15.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 386,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 187,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Vermicili Upma',
        nameHindi: 'वर्मिसिली उपमा',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: '7',
        isVegetarian: true,
        price: 30.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/c744fb5e-4732-4d50-b267-44a89719417d.jpg',
      },
      {
        id: 390,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 314,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Masala Tea',
        nameHindi: 'मसाला चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT51',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 391,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 305,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Ready Made Coffee',
        nameHindi: 'तैयार कॉफ़ी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'C1',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/9c29254e-e799-4d9b-a7e0-683db5bb9857.jpg',
      },
      {
        id: 490,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 323,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Veg Pasta',
        nameHindi: 'वेज पास्ता',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT60',
        isVegetarian: true,
        price: 50.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 491,
        availableQuantity: 5,
        masterCafeteriaMenuItemId: 482,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Tossed Salad',
        nameHindi: 'टॉस मिक्स सलाद',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'HS',
        isVegetarian: true,
        price: 25.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 540,
        availableQuantity: 10,
        masterCafeteriaMenuItemId: 184,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Mixed Vegetable Bhajia',
        nameHindi: 'मिश्रित सब्जी भजिया',
        descriptionEnglish: '(6 pcs)',
        descriptionHindi: '(6 पीस)',
        code: '15',
        isVegetarian: true,
        price: 50.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/c1e3d9a6-11f4-492f-8d71-d22b5790e4ab.jpg',
      },
    ],
  },
  {
    id: 16,
    day: 'Monday',
    cafeteriaMenuType: {
      id: 4,
      nameEnglish: 'All Day Menu',
      nameHindi: 'पूरे दिन का मेनू',
      startTime: '10:00:00',
      endTime: '17:30:00',
    },
    cafeteriaMenuItems: [
      {
        id: 192,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 68,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Green Tea',
        nameHindi: 'ग्रीन टी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'T8',
        isVegetarian: true,
        price: 16.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/821a9692-af8f-446e-9010-8a2dc6d10bdf.jpg',
      },
      {
        id: 194,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 305,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Ready Made Coffee',
        nameHindi: 'तैयार कॉफ़ी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'C1',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/9c29254e-e799-4d9b-a7e0-683db5bb9857.jpg',
      },
      {
        id: 232,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 306,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Kadha (Ayush)',
        nameHindi: 'काढ़ा (आयुष)',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'M192',
        isVegetarian: true,
        price: 12.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 237,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 221,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Masala Chaas',
        nameHindi: 'मसाला छाछ',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'M150',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/0cde256b-de6b-492c-992f-11d6c03b3d1b.jpg',
      },
      {
        id: 252,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 313,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Ready Made Tea',
        nameHindi: 'रेडी मेड चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT50',
        isVegetarian: true,
        price: 5.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath:
          'https://sansadcafeteria.blob.core.windows.net/public/mastermenuitem/150e4c6f-c41e-448e-b637-2229742d73fe.jpg',
      },
      {
        id: 257,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 314,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Masala Tea',
        nameHindi: 'मसाला चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT51',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 262,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 315,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Coffee',
        nameHindi: 'कॉफ़ी',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT52',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 297,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 310,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Namkeen',
        nameHindi: 'नमकीन',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT47',
        isVegetarian: true,
        price: 5.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 302,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 311,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Juices',
        nameHindi: 'जूस',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'WT48',
        isVegetarian: true,
        price: 20.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 334,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 383,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Earl Grey Tea',
        nameHindi: 'अर्ल ग्रे चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'T6',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
      {
        id: 338,
        availableQuantity: 25,
        masterCafeteriaMenuItemId: 349,
        maximumPerOrderQuantity: 5,
        nameEnglish: 'Darjeeling Tea',
        nameHindi: 'दार्जिलिंग चाय',
        descriptionEnglish: null,
        descriptionHindi: null,
        code: 'T5',
        isVegetarian: true,
        price: 10.0,
        isTaxable: true,
        taxRate: 5.0,
        photoStoragePath: null,
      },
    ],
  },
];
